### ISSUE TITLE
Stacktrace on Docker stop

### ISSUE THREAD

**Issue by luminosita** [mnikita/task-queue#2]
When docker container is stopped the following stacktrace show up in the log:

panic: send on closed channel

goroutine 21 [running]:

github.com/mnikita/task-queue/pkg/consumer.(*Consumer).handleConsume(0xc0000a4190)

/Users/milos/sandbox/task-queue/pkg/consumer/consumer.go:131 +0x239

github.com/mnikita/task-queue/pkg/consumer.(*Consumer).StartConsumer.func1(0xc0000a4190)

/Users/milos/sandbox/task-queue/pkg/consumer/consumer.go:194 +0x2b

created by github.com/mnikita/task-queue/pkg/consumer.(*Consumer).StartConsumer

/Users/milos/sandbox/task-queue/pkg/consumer/consumer.go:193 +0xf4

**Comment by luminosita** [comment]
Fixed with test
